### ISSUE TITLE
I-Search breaks mini-modeline

### ISSUE THREAD

**Issue by tsdh** [kiennq/emacs-mini-modeline#1]
I just tried out mini-modeline, and it's indeed a very interesting idea!

One thing I've noticed that after performing one isearch (where I cannot see my typed in search string), the mode-line will never ever be updated again.  I still see the `I-search: ` prompt at the beginning of the mini-modeline and also all other mode-line information like the (line,column) indicator or the current buffer name stays as its current value.  Even switching to another buffer will still show the old information.

![Screenshot-20190727095255-777x74](https://user-images.githubusercontent.com/103854/61991881-cc228080-b056-11e9-99b1-43fafc5835c0.png)

I can easily reproduce that with `emacs -Q` (using emacs master from git) by first manually loading `dash` and then `mini-modeline` and then activating that.

**Comment by kiennq** [comment]
Interesting, let me take a look.
Just asking but are you using the latest version?

**Comment by tsdh** [comment]
Yes, I installed it using Quelpa.

**Comment by kiennq** [comment]
Hmm, it doesn't happen to me. Can you check your *Message* buffer to see if anything goes wrong there?

**Comment by kiennq** [comment]
Can you check it again, it should be fixed with ada750e

**Comment by tsdh** [comment]
I'll try it whenever I find some spare time.

**Comment by tsdh** [comment]
@kiennq It works now.  Thanks a lot, I'm closing this issue.
