### ISSUE TITLE
Undesirable minibuffer size change before message

### ISSUE THREAD

**Issue by QiangF** [kiennq/emacs-mini-modeline#10]
When I have resize-mini-windows set to t, message three strings long enough to cause a line break consecutively, the minibuffer height will decrease to 1 line in between, which will cause screen flashes.
For example,  

    (run-at-time 1 nil (lambda () (message  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))
    (run-at-time 2 nil (lambda () (message  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))
    (run-at-time 3 nil (lambda () (message  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))

Some input methods uses the echo area to display word candidates, for a very long word or sentence, the constant flashing during updating is a nuisance.

When I have mini-modeline turned off, there is no flashing.

**Comment by kiennq** [comment]
Can you try `(setq mini-modeline-update-interval 0)` to see if it still happens?

**Comment by QiangF** [comment]
Yes, it still happens. (setq resize-mini-windows t) will stop it, but sometimes we need auto resize.

**Comment by QiangF** [comment]
The ugly workaround I found is

    (setq resize-mini-windows nil)

    (defun my-minibuffer-setup ()
    (setq resize-mini-windows t))

    (defun my-minibuffer-exit ()
    (setq resize-mini-windows nil))

    (add-hook 'minibuffer-setup-hook 'my-minibuffer-setup)
    (add-hook 'minibuffer-exit-hook 'my-minibuffer-exit)

And let mini-modeline always resize on redisplay

    (when mini-modeline--cache
    (if (>= (cdr mini-modeline--cache) 1)
        (window-resize (minibuffer-window mini-modeline-frame)
                        (- (cdr mini-modeline--cache)
                            (window-height (minibuffer-window mini-modeline-frame)))))

Apparently this will prevent mini-buffer auto resize between mini-modeline-display.

**Comment by kiennq** [comment]
Can you try capture a gif and show me what happened?

**Comment by QiangF** [comment]
[screen.txt](https://github.com/kiennq/emacs-mini-modeline/files/3628971/screen.txt)

**Comment by QiangF** [comment]
It's a mp4 file, please change file extension to view it. The converted gif file is too big.

**Comment by QiangF** [comment]
![anim](https://user-images.githubusercontent.com/8192731/65209207-f7ab6f80-dac9-11e9-8c6b-b460daed3524.gif)

**Comment by QiangF** [comment]
We must have

    (setq resize-mini-windows t)

or the modeline height won 't update if font size changes. see :
![img_2019_09_19__17_17_59](https://user-images.githubusercontent.com/8192731/65231948-ec286a80-db02-11e9-895a-661826766570.png)

**Comment by kiennq** [comment]
Yes, in mini-modeline-enable, I've already set `resize-mini-window` to t anyway.

I wonder what happens if you disable mini-modeline and resize the windows so the message will occupy 2 lines?
Wouldn't the same issue happens? I mean the minibuffer is jumping between 1 and 2 lines.

The less than ideal work around is using `mini-modeline-truncate-p` so the message echo in mini-modeline will have more spaces by pushing the mode line information to the right.
It's not like we need to see those information always though.

Or maybe we can try define new period that keep the mini buffer from resizing down.

**Comment by QiangF** [comment]
The problem is the resizing happens too quickly. If mini-modeline is disabled, 3 consecutive 2 line messages will keep the minibuffer size unchanged, no 1 line in between. Maybe increase the interval (greater than 5?) you will see 1 line, but that is not a problem for the eye.

So if you can define a new period that keep the mini buffer from resizing down, that will be ideal. 

I can not find which line in the source causes the resize, not erase-buffer, not message nil.

Set trucate to t will be problematic for multiple line message.
Sent using Zoho Mail


---- On 星期四, 2019-09-19 17:43:38 notifications@github.com wrote ----

Yes, in mini-modeline-enable, I've already set resize-mini-window to t anyway.

I wonder what happens if you disable mini-modeline and resize the windows so the message will occupy 2 lines?
Wouldn't the same issue happens? I mean the minibuffer is jumping between 1 and 2 lines.

The less than ideal work around is using mini-modeline-truncate-p so the message echo in mini-modeline will have more spaces by pushing the mode line information to the right.
It's not like we need to see those information always though.

Or maybe we can try define new period that keep the mini buffer from resizing down.

**Comment by QiangF** [comment]
With mini-modeline disabled, the minibuffer only resize when new messages arrives. Try this :

    (setq resize-mini-windows t)
    (run-at-time 1 nil
                (lambda ()
                (message  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                (cancel-function-timers 'my-gif-screencast-capture)))
    (run-at-time 6 nil
                (lambda ()
                (message  "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                (cancel-function-timers 'my-gif-screencast-capture)))
    (run-at-time 11 nil
                (lambda ()
                (message  "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")
                (cancel-function-timers 'my-gif-screencast-capture)))

See the echoed message doesn 't change. You have to adjust your font big enough or increase the string length by adding more characters for the strings to occupy two lines.

**Comment by QiangF** [comment]
For comparison:

    (mini-modeline-mode 1)
    (setq resize-mini-windows t)
    (run-at-time 1 nil
                (lambda ()
                (message  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")))
    (run-at-time 6 nil
                (lambda ()
                (message  "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")))
    (run-at-time 11 nil
                (lambda ()
                (message  "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")))
