### ISSUE TITLE
'%' sign in mini-buffer causes error

### ISSUE THREAD

**Issue by walseb** [kiennq/emacs-mini-modeline#15]
If there is a percent sign being displayed in the minibuffer, mini-modeline throws an error
Stacktrace:
```
Debugger entered--Lisp error: (error "Format string ends in middle of format specifier")
  #<subr message>("test%")
  apply(#<subr message> "test%")
  mini-modeline--reroute-msg(#<subr message> "test%")
  apply(mini-modeline--reroute-msg #<subr message> "test%")
  message("test%")
  eval((message "test%") nil)
  eval-expression((message "test%") nil nil 127)
```

Steps to reproduce:
1. `emacs -Q`
2. load `emacs-mini-modeline`
3. `M-x toggle-debug-on-error`
3. `M-x eval-expression` and insert `(message "test%")`

**Comment by kiennq** [comment]
I'm pretty sure that if you eval `(message "test%")` without `emacs-mini-modeline` it still throw error.
The "%" without anything follow is malformed format string, if you want to print `%` in emacs, you have to use `%%`.

With that said, for unrelated issue, I see that `mini-modeline` is not display `%` correctly sometimes, I will fix that.

**Comment by kiennq** [comment]
With 8762d2ec, now `(message "a%%")` will correctly display `a%` with `mini-modeline`

**Comment by walseb** [comment]
Ah I see, I didn't think it could be related to message itself because the trace seemed to suggest it was a problem with this package. Thanks!

**Comment by kiennq** [comment]
> Ah I see, I didn't think it could be related to message itself because the trace seemed to suggest it was a problem with this package. Thanks!

I intercept the `message` function to have it play nice with `mini-modeline`, that why you see it in the trace. However, these line
```
Debugger entered--Lisp error: (error "Format string ends in middle of format specifier")
  #<subr message>("test%")
  apply(#<subr message> "test%")
```
suggests that the problem is from `message` itself.
