### ISSUE TITLE
Handle read-key?

### ISSUE THREAD

**Issue by AmaiKinono** [kiennq/emacs-mini-modeline#17]
I'm using straight.el to manage my Emacs packages. Its popup is not displayed right when using mini-modeline:

![read-key](https://user-images.githubusercontent.com/28714352/75968239-036be080-5f08-11ea-81f1-f2d2f49f9c69.gif)

You can see this is a multi-line prompt. When I press some arrow key, they can show for a while but then folds to 1 line (it's in a loop so it calls `read-key` again when I don't press the right key).

I looked into the code. straight.el uses `read-key` for this, and I saw the thing you did with `read-key-sequence`. So I tried wrap it with `mini-modeline--wrap` like you did. But this doesn't work.

**Comment by kiennq** [comment]
@AmaiKinono Can you try with latest version, I think it should be fixed now

**Comment by AmaiKinono** [comment]
No. It looks like this now. It's not folded but hidden:

![Peek 2020-03-06 10-52](https://user-images.githubusercontent.com/28714352/76045762-04991e00-5f99-11ea-8721-466de406cc33.gif)

You can test with this one-liner:

``` emacs-lisp
(while (not (eq (read-key "multi\nline\nprompt") ?\C-g)))
```

**Comment by kiennq** [comment]
Not happen to me with the latest version though.
Can you check if you're using the `origin/master` already?
I think you're using `straight.el` which will have some problem with pulling the `origin/master` that deviates from current `HEAD`.
Or you can try just deleting this package and reinstall it via `package-install` or using `Quelpa`.

**Comment by AmaiKinono** [comment]
I am on the latest master. I've found the problem: It has something to do with `blink-cursor-mode` (yeah that's weird). Try this in `emacs -Q`:

``` emacs-lisp
(require 'mini-modeline)
(blink-cursor-mode -1)
(mini-modeline-mode)
(while (not (eq (read-key "multi\nline\nprompt") ?\C-g)))
```
Then press some key that's not `C-g`.

**Comment by kiennq** [comment]
Even with `blink-cursor-mode` disabled, I still cannot repro this 😞 
If you look at my gif, the `blink-cursor-mode` has been disabled.

**Comment by AmaiKinono** [comment]
I'm using Emacs 26.3 on Linux. What version are you using? If it's different, I could install and test it tomorrow.

**Comment by kiennq** [comment]
I'm using emacs-snapshot 27.0.

**Comment by AmaiKinono** [comment]
I'm on Emacs 27.0.90 now. The problem still happens, and I can tell you that `mini-modeline-mode` strongly interferes with `blink-cursor-mode`.

![blink-cursor-mode](https://user-images.githubusercontent.com/28714352/76136676-0b926000-606f-11ea-9850-5a3a4177305b.gif)

This is `emacs -Q` and I didn't do anything other than the code you see in the screenshot (so `blink-cursor-mode` is on, by default). After enabling `mini-modeline-mode`:

- The cursor stops blinking.
- When I type something, the cursor shows and immediately disappears. The GIF is not well recorded so it looks like glitching, but actually the cursor just gone.
- When I move to somewhere, the cursor appears again and doesn't blink.

I didn't remember if I saw this in 26.3. One thing that's different from 26.3 is if I disable and enable `blink-cursor-mode` again, the read-key prompt shows correctly.

Did you notice this behavior in `emacs -Q`? If you didn't than I really don't know what's wrong... maybe switch to another PC and test it again.

**Comment by AmaiKinono** [comment]
Ok, here's the situation now: You can merge #20, it solves the cursor problem perfectly. The thing described below has nothing to do with `blink-cursor-mode` since I've test them with `blink-cursor-mode` enabled and disabled.

In `emacs -Q`, when you test using this one liner:

``` emacs-lisp
(while (not (eq (read-key "multi\nline\nprompt") ?\C-g)))
```

when pressing any key, the prompt foldes into one line and expands really quick. It looks like a blink so that's perfectly useable. I don't know what you see, does it blink or not?

In my own config, somehow the reaction is slow. When I press a key, it needs like 0.5s to fold, then another 0.5s to expand. So it doesn't look good, but useable too. This is affected by `mini-modeline-update-interval`, but even it's set to 0.0, the reaction is still slow.

I can't do more test since even if I leave only configurations of straight.el, use-package and mini-modeline, it's still slow.

You can take this issue as solved (since it's already useable). But don't close it for now, please let me confirm this also works on 26.3 later.

**Comment by kiennq** [comment]
When I've tried with Ubuntu, I did saw the blinking of minibuffer being expanded/retracted.
However, with Emacs on Windows, the problem don't happen.
Not sure why

**Comment by kiennq** [comment]
@AmaiKinono Can you try with latest master, it seems that the issues is fixed in my Ubuntu Emacs

**Comment by AmaiKinono** [comment]
Yes, it fixes the issue in both 27.0 and 26.3 :tada: Now the minibuffer window is super solid when test.

**Comment by kiennq** [comment]
Thanks, I'm closing this issue, please open it again if you have found new undesired behaviors

**Comment by AmaiKinono** [comment]
I have to reopen this. With https://github.com/kiennq/emacs-mini-modeline/commit/6b6efe6ba337440b18052d5699ad3334bd80c1cc, `read-from-minibuffer` with multi-line prompt/content doesn't work. Try this:

``` emacs-lisp
(read-from-minibuffer "Hi: " "line1\nline2")
```

**Comment by kiennq** [comment]
Let's track the new issue with #23
