### ISSUE TITLE
6b6efe6 regress `read-from-minibuffer`

### ISSUE THREAD

**Issue by kiennq** [kiennq/emacs-mini-modeline#23]
The comment here https://github.com/kiennq/emacs-mini-modeline/issues/17#issuecomment-596168598

**Comment by kiennq** [comment]
@AmaiKinono Can you check with the attached PR to see if the problem is resolved?

**Comment by AmaiKinono** [comment]
Yes, it's solved. My only concern is if this will happen in other commands too. But you are definitely more familiar with echo area/minibuffer related things. So I'm gonna trust you ;)

**Comment by kiennq** [comment]
> Yes, it's solved. My only concern is if this will happen in other commands too. But you are definitely more familiar with echo area/minibuffer related things. So I'm gonna trust you ;)

Thanks. I've set it up when enter minibuffer so it should not affect other minibuffer related commands. For commands that echo into echo area, @QiangF has excellent solution of manually resize minibuffer, so we should be good
