### ISSUE TITLE
Minibuffer prompt changes color

### ISSUE THREAD

**Issue by johnmwu** [kiennq/emacs-mini-modeline#26]
![image](https://user-images.githubusercontent.com/36543782/76893002-faf99b00-6861-11ea-9509-69de712672d9.png)
Normally, this is what `C-x C-f` looks like, but when `mini-modeline-mode` enabled, I get:
![image](https://user-images.githubusercontent.com/36543782/76893092-22e8fe80-6862-11ea-8354-3e66240d6e21.png)

I'm using smart-mode-line with the manoj-dark theme. As far as I can tell, though, this weird color change happens with all dark themes.

**Comment by johnmwu** [comment]
Oh lol, was fixed with 

`(setq mini-modeline-color "black")`

**Comment by kiennq** [comment]
Alternatively, if you don't like new color when focusing on minibuffer, you can set `mini-modeline-enhance-visual` to `nil`
