### ISSUE TITLE
Add option to remove gui line

### ISSUE THREAD

**Issue by n8m4** [kiennq/emacs-mini-modeline#28]
Could you add option to remove gui line that is showed above minibuffer?

**Comment by redrubyread** [comment]
The following code might help you

```
(when (display-graphic-p)
  (setf (alist-get 'mode-line face-remapping-alist)
        'default))

(defun pes-mini-windows-change-hook  ()
    (if (> (count-windows) 1)
      (when (display-graphic-p)
        (setf (alist-get 'mode-line face-remapping-alist)
              'mini-modeline-mode-line-inactive)
        (setf (alist-get 'mode-line-inactive face-remapping-alist)
              'default))
      (when (display-graphic-p)
        (setf (alist-get 'mode-line face-remapping-alist)
              'default))))

(add-hook 'window-configuration-change-hook #'pes-mini-windows-change-hook)

```
@n8m4

**Comment by kiennq** [comment]
Or can you try to customize `mini-modeline-mode-line` and `mini-modeline-mode-line-inactive` face?
``` elisp
(custom-theme-set-faces
 'user
 `(mini-modeline-mode-line ((t (:inherit default :height 0.1 :box nil))) t)
 `(mini-modeline-mode-line-inactive ((t (:inherit default :height 0.1 :box nil))) t))
```

**Comment by andreyorst** [comment]
while this solves the problem it also absolutely kills everything that inherits mofeline face by making the text tiny.

In the code I see that in case when Emacs is ran in the terminal you simply set `mode-line-format` to `nil`, and In GUI this will work just as fine. With window divider mode you can distinguish vertical windows, the only problem left is how to differenciate active window. I display the cursor only in the active window with `(setq-default cursor-in-non-selected-windows nil)`, and with that I don't need modeline at all, so an option to disable modeline completely without breaking the face inheritance will be a nice addition to this package.
