### ISSUE TITLE
Titlebar became unreadable

### ISSUE THREAD

**Issue by jumper047** [kiennq/emacs-mini-modeline#31]
When mini-modeline mode activated titlebar become as thin as active window indicator. You can see it running "list-packages", for example.

**Comment by kiennq** [comment]
> When mini-modeline mode activated titlebar become as thin as active window indicator. You can see it running "list-packages", for example.

Which title bar are you referring to? Can you show me in some screenshot?

**Comment by jumper047** [comment]
![img-2020-05-21-002945](https://user-images.githubusercontent.com/1407838/82499588-932e2d80-9afa-11ea-9e2f-d8230689d1f8.png)
![img-2020-05-21-003111](https://user-images.githubusercontent.com/1407838/82499635-b0fb9280-9afa-11ea-8627-a7b6ce01c9ed.png)

I am talking about bar which contain column's names - in the top at first picture. On second he became thin and blue, just like bar on bottom of screen. Interesting that he became like this not immediately but after some minutes when i activate mini modeline mode.

**Comment by kiennq** [comment]
Can you check the face for `header-line` when this repro? I cannot seem to able to repro this

**Comment by jumper047** [comment]
Checked - header-line inherits mode-line face, so i can fix it myself:). Btw i use doom-themes, quite popular package. May be this issue worth to mention in readme? Or it is more correct to open issue in doom-themes?

**Comment by kiennq** [comment]
Yes, I think `header-line` should not inherit from `mode-line`. I'm using `zenburn` and it's quite ok. So `doom-themes` should fix it. Decoupling between `mode-line` and `head-line` and even `tab-line` would be the best.

**Comment by jumper047** [comment]
Seems like i can close issue now - issue completely fixed.
