### ISSUE TITLE
After load-theme invocation minibuffer's background's color not changing

### ISSUE THREAD

**Issue by jumper047** [kiennq/emacs-mini-modeline#32]
At emacs launch i set light theme - all looks as intended:
![img-2020-05-23-140748](https://user-images.githubusercontent.com/1407838/82730704-6e100980-9d0a-11ea-890f-3be18791de92.png)
Then I change theme to dark one, but minibuffer's background remains light:
![img-2020-05-23-140927](https://user-images.githubusercontent.com/1407838/82730736-a9aad380-9d0a-11ea-9e8b-ea63e9515eda.png)
Modeline itself changes color to themed one.
![img-2020-05-23-153352](https://user-images.githubusercontent.com/1407838/82730766-f1c9f600-9d0a-11ea-80c5-4c88d5174585.png)

I figured out how to fix it for myself, but i think it worth to report anyway.

**Comment by jumper047** [comment]
BTW - is mini modeline background color supposed to be setted up in mini-modeline-face-attr? It does'nt work for me - after first minibuffer usage it changed color to background. Is it a bug?

**Comment by kiennq** [comment]
How did you set that value?

**Comment by kiennq** [comment]
You can try set `mini-modeline-face-attr` to `(:inherit default)` to see if it can fix your problem

**Comment by jumper047** [comment]
I don't set it at all - bug appears with default value. `:inherit default`, of course, fixes an issue

**Comment by kiennq** [comment]
@jumper047 Do you still experience this issue? You can set `mini-modeline-face-attr` to inherit some nice highlight face, and will will change color altogether with theme.

**Comment by ChanderG** [comment]
I think @jumper047 's point was, and I agree having faced this issue now, that '(:inherit default) should be the default value for mini-modeline-face-attr.
