### ISSUE TITLE
GUI line not showing with server-mode

### ISSUE THREAD

**Issue by slotThe** [kiennq/emacs-mini-modeline#37]
With the following `init.el`

```emacs-lisp
(require 'mini-modeline)
(mini-modeline-mode)
```

the GUI line initially fails to draw when using emacs as a server and spawning new buffers via emacsclient.  It does work if one evaluates `(mini-modeline-mode t)` manually (or just toggles the mode off and back on again), but doing so every time another emacs server is started is kinda tedious.  When starting emacs normally (i.e. without `server-mode`) everything is showing correctly.

Any idea?

**Comment by kiennq** [comment]
It's because when emacs start as server, it will run as terminal Emacs. At that time, `mini-modeline-mode` will detect that Emacs has no GUI capability and disable the GUI line.
The easiest fix is to enable `mini-modeline-mode` once in `focus-in-hook`.

**Comment by slotThe** [comment]
On Wed, Aug 12 2020 03:14, kiennq wrote:
> It's because when emacs start as server, it will run as terminal Emacs. At that time, `mini-modeline-mode` will detect that Emacs has no GUI capability and disable the GUI line.
> The easiest fix is to enable `mini-modeline-mode` once in `focus-in-hook`.

Ah, didn't think of that.  Worked like a charm, thanks!
