### ISSUE TITLE
FYI: similar package you may be interested

### ISSUE THREAD

**Issue by QiangF** [kiennq/emacs-mini-modeline#4]
http://www.emacswiki.org/emacs/download/awesome-tray.el

also EXWM with minibuffer-auto-raise set to true.

**Comment by kiennq** [comment]
Thanks.

I've first heard of that package when I try to pr my package on [reddit](https://www.reddit.com/r/emacs/comments/cfovww/minimodeline_display_mode_line_in_minibuffer/).
AFAIK, there're some similar packages to mine:
- [feebleline](https://github.com/tautologyclub/feebleline/)
- [awesome-tray](https://github.com/manateelazycat/awesome-tray)
- [minibuffer-line](https://elpa.gnu.org/packages/minibuffer-line.html)

The main differences with those packages are:
- You can bring the modeline as it to minibuffer. The other only offer a slim down version of modeline or only some predefined components only. I'm not sure how much you can customize it.
- I've gone to a great length of trying to merge the echo area and modeline in minibuffer.
  - Intercept `message` to display message on placeholder in minibuffer. `awesome-tray` did the same though.
  - Intercept `current-message` and merge them to minibuffer
  - Disable `echo-keystrokes` when needed
  - Other small optimization to make sure you don't have to sacrifice perf more than when you turn on mode line.
  - etc ....

I'm not listing those differences in my README since I'm not aware of those packages when I first created mine though.

**Comment by QiangF** [comment]
Thank you for the clarification. The emacs window manager (exwm) does the space saving by auto hide the echo area. It might be a better choice if the user does not run emacs alone.
Sent using Zoho Mail


---- On 星期六, 2019-08-24 21:12:45 notifications@github.com wrote ----

Thanks.

I've first heard of that package when I try to pr my package on reddit.
AFAIK, there're some similar packages to mine:

feebleline
awesome-tray
minibuffer-line
The main differences with those packages are:

You can bring the modeline as it to minibuffer. The other only offer a slim down version of modeline or only some predefined components only. I'm not sure how much you can customize it.
I've gone to a great length of trying to merge the echo area and modeline in minibuffer.
Intercept message to display message on placeholder in minibuffer. awesome-tray did the same though.
Intercept current-message and merge them to minibuffer
Disable echo-keystrokes when needed
Other small optimization to make sure you don't have to sacrifice perf more than when you turn on mode line.
etc ....
I'm not listing those differences in my README since I'm not aware of those packages when I first created mine though.

**Comment by QiangF** [comment]
I have just tried mini-modeline, the displayed string is build onformat-mode-line, which makes it a lot simpler thanawesome-tray. But I think the philosophy behind awesome-tray iscorrect, we don't need so much infomation displayed. It's wouldbe much better if you can let the message and modeline infodisplaed in the same time. I went through the code, and found inmini-modeline the message is inhibited. In awesome-traythe two are concatenated, also newline will be added depends on the message length.
See:

    (defun awesome-tray-message-advice (old-message &rest arguments)
    (condition-case nil
            (if awesome-tray-active-p
            (progn (cond
                    ;; Just flush tray info if message string is empty.
                    ((not (car arguments))
                        (apply old-message arguments)
                        (awesome-tray-flush-info))
                    ;; Otherwise, wrap message string with tray info.
                    (t
                        (apply old-message "%s" (cons (awesome-tray-get-echo-format-string (apply 'format arguments)) '())))))
            (apply old-message arguments))
        (apply old-message arguments)
    ))

    (defun awesome-tray-get-echo-format-string (message-string)
    (let* ((tray-info (awesome-tray-build-info))
            (blank-length (- (frame-width) (string-width tray-info) (string-width message-string) awesome-tray-info-padding-right))
            (empty-fill-string (make-string (max 0 (- (frame-width) (string-width tray-info) awesome-tray-info-padding-right)) ?\ ))
            (message-fill-string (make-string (max 0 (- (frame-width) (string-width message-string) (string-width tray-info) awesome-tray-info-padding-right)) ?\ )))
        (prog1
            (if (> blank-length 0)
                ;; Fill message's end with whitespace to keep tray info at right of minibuffer.
                (concat message-string message-fill-string tray-info)
            (if (and awesome-tray-last-tray-info
                    message-string
                    (string-suffix-p awesome-tray-last-tray-info message-string))
                ;; Fill empty whitespace if new message contain duplicate tray-info (cause by move mouse on minibuffer window).
                (concat empty-fill-string tray-info)
                ;; Don't fill whitepsace at end of message if new message is very long.
                (concat message-string "\n" (concat empty-fill-string tray-info))))
        ;; Record last tray information.
        (setq awesome-tray-last-tray-info tray-info))))

**Comment by kiennq** [comment]
Thanks for your interest :)

> But I think the philosophy behind awesome-tray iscorrect, we don't need so much infomation displayed. It's wouldbe much better if you can let the message and modeline infodisplaed in the same time.

I think we already have message and modeline displayed at the same time with mini-mode-line.
What you mean is the behavior of the gif in [README](https://github.com/kiennq/emacs-mini-modeline/blob/master/README.md) right?

Also, here is the place holder that needed to be added to `mini-modeline-l-format` (or `mini-modeline-r-format`) if you want the message to be concatenate with the modeline info:
``` elisp
(:eval (mini-modeline-msg))
```
I think it's the default value for `mini-modeline-l-format` already though.

**Comment by kiennq** [comment]
Also, PRs are always welcome :)
