### ISSUE TITLE
Modeline background is all white

### ISSUE THREAD

**Issue by nixin72** [kiennq/emacs-mini-modeline#42]
I have the following configuration for my `mini-modeline`:
```
(straight-use-package 'mini-modeline)
(progn
  (setq mini-modeline-r-format
        '("%e" (:eval (number-to-string (winum-get-number)))
               " "
               evil-mode-line-tag
               " "
               mode-line-modified
               mode-line-buffer-identification
               " "
               mode-line-position
               (:eval (symbol-name major-mode))
               "   "
               (:eval (magit-get-current-branch))
               "   "
               (:eval (format-time-string "%l:%M%P")))
        mini-modeline-l-format nil)
  (mini-modeline-mode t))
```
And it was working fine right after I installed it to replace `doom-modeline` but when I restarted Emacs, the background for the minibuffer is just all white when `mini-modeline-mode` is on. I turn it off and it's black as expected, but then turning it back on just makes the minibuffer white again. I can't figure out what's causing this as it was working before and I don't have any configuration related to colours :man_shrugging:

**Comment by kiennq** [comment]
Can you check the value of `mini-modeline-face-attr`? You can set it to visible background.

**Comment by nixin72** [comment]
Changing that value fixed it, thank you!
