### ISSUE TITLE
mini-modeline hides messages

### ISSUE THREAD

**Issue by diamond-lizard** [kiennq/emacs-mini-modeline#44]
With mini-modeline active, when I eval ```(message "foo")``` I expect to see ```"foo"``` in the minibuffer, but instead I only briefly see: ```nil```

So it seems that mini-modeline is hiding messages that would normally appear in the minibuffer.

**Comment by AmaiKinono** [comment]
I believe it's because the advice in `mini-modeline` makes `message` return nil. Try this in vanilla Emacs:

``` elisp
(message "foo")
```

Call `eval-last-sexp` on it, this is write to `*Messages*` buffer:

```elisp
foo   ;; This is the message
"foo" ;; This is the return value of `message'
```

With `mini-modeline-mode`, it's:

```elisp
foo  ;; The message
nil  ;; The return value
```

So actually this is not a problem for `message` calls in elisp programs.
