### ISSUE TITLE
Add some features

### ISSUE THREAD

**Issue by QiangF** [kiennq/emacs-mini-modeline#6]
I am terrible at using git, and you might disagree with me, so I create this issue instead of a pull requqest.
1. Add an extra line break if the first line is longer than frame width: usually the mini-modeline should be just one line, so handle the first line as an exception is enough to make things look nice.
2. Add mini-modeline-frame: some users use the exwm emacs window manager, the frame that the minibuffer is displayed on is exwm-workspace--current, which could be different from the frame in focus.

This is lisp code:

     (defvar mini-modeline-frame nil)

     (defsubst mini-modeline-lr-render (left right)
         "Render the LEFT and RIGHT part of mini-modeline."
         (let* ((available-width (- (frame-width mini-modeline-frame) (string-width left) 2))
             (required-width (string-width right)))
         (if (< available-width required-width)
             (format (format "%%%ds\n%%s" (frame-width mini-modeline-frame)) right left)
             (format (format "%%s %%%ds" available-width)
                     (or left "")
                     (or right "")))))

     (defun mini-modeline--multi-lr-render (left right)
         "Render the LEFT and RIGHT part of mini-modeline with multiline supported.
     Return value is (STRING . LINES)."
         (let* ((l (split-string left "\n"))
             (r (split-string right "\n"))
             (lines (max (length l) (length r)))
             re extra-lines)
         (--dotimes lines
             (setq re (nconc re `(,(mini-modeline-lr-render (elt l it) (elt r it))))))
         (setq extra-lines (cl-count ?\n (car re)))
         (cons (string-join re "\n") (+ lines extra-lines))))

After using it for several days, I found that mini-modeline-mode is better than many other packages: it doesn 't pollute my Message buffer.
Here is my current configs if anyone is interested:

    (use-package mini-modeline
    :commands mini-modeline-mode
    :init
    (if exwm_enable 
        (add-hook 'exwm-init-hook #'mini-modeline-mode t)
        (add-hook 'after-init-hook #'mini-modeline-mode t))
    :config
    (when (and exwm_enable (exwm-workspace--minibuffer-own-frame-p))
        (add-hook 'mini-modeline-mode-hook #'exwm-workspace-attach-minibuffer))
    (add-hook 'focus-in-hook 'mini-modeline-display)
    (setq display-time-day-and-date nil)
    (setq mini-modeline-echo-duration 4)
    (display-time-mode t)
    (unless exwm_enable (setq exwm-workspace--current nil))

    (defvar symon-refresh-rate 4)
    (defvar symon-linux--last-network-rx nil)
    (defvar symon-linux--last-network-tx nil)
    (defvar my-last-symon-message "")

    (defun symon-linux--read-lines (file reader indices)
        (with-temp-buffer
        (insert-file-contents file)
        (goto-char 1)
        (mapcar (lambda (index)
                    (save-excursion
                    (when (search-forward-regexp (concat "^" index "\\(.*\\)$") nil t)
                        (if reader
                            (funcall reader (match-string 1))
                        (match-string 1)))))
                indices)))

    (defun my-update-symon ()
        (setq my-last-symon-message
            (concat
            ;; Receive speed
            (format "R:%s "
                    (with-temp-buffer
                        (insert-file-contents "/proc/net/dev")
                        (goto-char 1)
                        (let ((rx 0))
                        (while (search-forward-regexp "^[\s\t]*\\(.*\\):" nil t)
                            (unless (string= (match-string 1) "lo")
                            (setq rx (+ rx (read (current-buffer))))))
                        (prog1 (when symon-linux--last-network-rx
                                    (/ (- rx symon-linux--last-network-rx) symon-refresh-rate 1000))
                            (setq symon-linux--last-network-rx rx)))))
            ;; Transmit speed
            (format "T:%s " 
                    (with-temp-buffer
                        (insert-file-contents "/proc/net/dev")
                        (goto-char 1)
                        (let ((tx 0))
                        (while (search-forward-regexp "^[\s\t]*\\(.*\\):" nil t)
                            (unless (string= (match-string 1) "lo")
                            (forward-word 8)
                            (setq tx (+ tx (read (current-buffer))))))
                        (prog1 (when symon-linux--last-network-tx
                                    (/ (- tx symon-linux--last-network-tx) symon-refresh-rate 1000))
                            (setq symon-linux--last-network-tx tx)))))
            ;; memory
            (format  "M:%s"
                        (cl-destructuring-bind (memtotal memavailable memfree buffers cached)
                            (symon-linux--read-lines
                            "/proc/meminfo" (lambda (str) (and str (read str)))
                            '("MemTotal:" "MemAvailable:" "MemFree:" "Buffers:" "Cached:"))
                        (if memavailable
                            (/ (* (- memtotal memavailable) 100) memtotal)
                            (/ (* (- memtotal (+ memfree buffers cached)) 100) memtotal))))
            ;; swapped
            (cl-destructuring-bind (swaptotal swapfree)
                (symon-linux--read-lines
                    "/proc/meminfo" 'read '("SwapTotal:" "SwapFree:"))
                (let ((swapped (/ (- swaptotal swapfree) 1000)))
                (unless (zerop swapped) (format " %dMB Swapped" swapped))))
            )))

    (display-battery-mode 1)
    (defun awesome-tray-module-symon-info ()
        (if (string-empty-p battery-mode-line-string)
            my-last-symon-message
        (concat my-last-symon-message " " battery-mode-line-string)))
    (setq awesome-tray-symon-timer (run-with-timer 0 symon-refresh-rate 'my-update-symon))

    (defun awesome-tray-module-workspace-info ()
        (let ((workspace-str ""))
        (when (bound-and-true-p ace-window-display-mode)
            (setq workspace-str
                (concat workspace-str (window-parameter (selected-window) 'ace-window-path))))
        (when (boundp 'exwm-workspace-current-index)
            (setq workspace-str
                (concat workspace-str
                        (propertize (int-to-string exwm-workspace-current-index) 'face '((:background "#0000ff" :foreground "#ffff00"))))))
        (when (and (bound-and-true-p eyebrowse-mode)
                    (< 1 (length (eyebrowse--get 'window-configs))))
            (let* ((num (eyebrowse--get 'current-slot))
                (tag (when num (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
                (str (if (and tag (< 0 (length tag)))
                            tag
                        (when num (int-to-string num)))))
            (when str
                (setq workspace-str (concat workspace-str (format ":%s" str))))))
        workspace-str))

    (defun roife/shorten-path (path &optional max-len)
        "Shorten PATH to MAX-LEN."
        (unless max-len (setq max-len 0))
        (if (and path (not (eq path "")))
            (let* ((components (split-string (abbreviate-file-name path) "/"))
                (len (+ (1- (length components))
                        (reduce '+ components :key 'length)))
                (str ""))
            (while (and (> len max-len)
                        (cdr components))
                (setq str (concat str (if (= 0 (length (car components)))
                                        "/"
                                        (string (elt (car components) 0) ?/)))
                    len (- len (1- (length (car components))))
                    components (cdr components)))
            (concat str (reduce (lambda (a b) (concat a "/" b)) components)))
        ""))

    (defvar my-buffer-id-length 50 "")

    (defun my-trim-buffer-id (id suffix-length)
        (if (> (length id) my-buffer-id-length)
            (concat (substring id 0 (- my-buffer-id-length suffix-length))
                    (substring id (- 0 suffix-length)))
        id))

    (defun my-buffer-id ()
    (cond ((buffer-file-name)
            (let* ((file-name (roife/shorten-path (buffer-file-name) my-buffer-id-length)))
            (if (<= (string-width file-name) my-buffer-id-length)
                file-name
                (my-trim-buffer-id (buffer-name) 4))))
            ((and exwm_enable (derived-mode-p 'exwm-mode))
            (my-trim-buffer-id exwm-title 10))
            (t (if (buffer-name) (my-trim-buffer-id (buffer-name) 4) ""))))

    ;; "chartreuse3"
    ;; Color the evil tag - colors taken from spaceline
    (setq evil-normal-state-tag   (propertize "N" 'face '((:background "DarkGoldenrod2" :foreground "black")))
            evil-emacs-state-tag    (propertize "E" 'face '((:background "SkyBlue2"       :foreground "black")))
            evil-insert-state-tag   (propertize "I" 'face '((:background "red"            :foreground "black")))
            evil-replace-state-tag  (propertize "R" 'face '((:background "chocolate"      :foreground "black")))
            evil-motion-state-tag   (propertize "M" 'face '((:background "plum3"          :foreground "black")))
            evil-visual-state-tag   (propertize "V" 'face '((:background "red"            :foreground "black")))
            evil-operator-state-tag (propertize "O" 'face '((:background "sandy brown"    :foreground "black"))))

    (setq display-time-24hr-format t)
    (setq display-time-mail-string "")
    (setq display-time-string-forms
            '((propertize (format-time-string "%H:%M" now) 'face '((:background "#140004" :foreground "green")))))

    (set-face-attribute 'mode-line-buffer-id nil :foreground "red")
    ;; mode-line-mule-info: 当前内容的编码和输入法，U指UTF-8
    ;; mode-line-modified: **已经被修改，--没被修改，%%表示只读，%* 表示内容只读并且被修改
    (setq mini-modeline-r-format '("%e"
                                    ;; (:eval (format-mode-line (propertized-buffer-identification "%b")))
                                    (:eval (propertize (my-buffer-id) 'face '((:background "#000000" :foreground "red"))))
                                    " "
                                    mode-line-position
                                    ;; (vc-mode vc-mode)
                                    mode-line-remote
                                    evil-mode-line-tag
                                    mode-line-mule-info
                                    mode-line-modified
                                    " "
                                    (:eval (awesome-tray-module-workspace-info))
                                    ;; (:eval (propertize (awesome-tray-module-workspace-info) 'face '((:background "#002555" :foreground "#ffff00"))))
                                    " "
                                    display-time-string
                                    " "
                                    (:eval (propertize (awesome-tray-module-symon-info) 'face 'font-lock-warning-face))
                                    ))
        (defun my-clear-echo-area ()
        (let ((mini-modeline--msg-message ""))
            (mini-modeline-display 'force)))
        (when (featurep 'pyim)
        (advice-add 'pyim-terminate-translation :after 'my-clear-echo-area)))

**Comment by QiangF** [comment]
Git hub is terrible at formating my text.

**Comment by kiennq** [comment]
Sorry for late reply, I forgot to watch this repo so no notification is received :)
Let me take a look at your propose.
