### ISSUE TITLE
vc-status does not appear

### ISSUE THREAD

**Issue by arkhan** [kiennq/emacs-mini-modeline#8]
regards

Great job, I am configuring but notice that activating mini-modeline disappears vc-status.

I attach behavioral captures

![output-2019-09-10-13:16:47](https://user-images.githubusercontent.com/3141865/64639404-62272600-d3cd-11e9-91d3-3cb462013104.gif)

How can I solve it.

Thank you

**Comment by kiennq** [comment]
You can customize `mini-modeline-r-format` to include `vc-status`.
It's the same format type as `mode-line-format` so you can probably just copy it over the new one.
Also, please refer to Readme.md for further customization

**Comment by arkhan** [comment]
It works well

![img-2019-09-11-131819](https://user-images.githubusercontent.com/3141865/64723701-a6322d80-d496-11e9-9690-9dd18c1652db.png)

Thanks

**Comment by kiennq** [comment]
Nice :)
